### ISSUE TITLE
regular expression support

### ISSUE THREAD

**Issue by justin-hackin** [andybluntish/ember-cli-replace#1]
With the following:
```
   patterns: [{
      match: '/bar/g',
      replacement: 'foo' 
    }, {
      match: 'foo',
      replacement: 'bar' // replaces "@@foo" to "bar"
    }]
```
'@@foo' is replaced by 'bar' but 'bar' is not replaced by 'foo' in my document

**Comment by andybluntish** [comment]
G'day.

It looks like you're using a `String` instead of a `RegExp` object for the `match` parameter. To get regular expression matching, make sure you pass in a `RegExp`, as per the [broccoli-replace documentation](https://github.com/outaTiME/broccoli-replace#patternsmatch):

    patterns: [{
      match: /bar/g, // quotes removed
      replacement: 'replaced_bar'
    }, {
      match: 'foo',
      replacement: 'replaced_foo'
    }]

Since you're currently using a `String`,  is actually doing variable replacement, and looking for "@@/bar/g".

Hope this helps. Cheers.

**Comment by justin-hackin** [comment]
:+1:
